# This rule is not used by the project greeter-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to hello.hello.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: greeter-operator
    app.kubernetes.io/managed-by: kustomize
  name: greeter-viewer-role
rules:
- apiGroups:
  - hello.hello.io
  resources:
  - greeters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello.hello.io
  resources:
  - greeters/status
  verbs:
  - get
