---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hello.hello.io
  resources:
  - greeters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hello.hello.io
  resources:
  - greeters/finalizers
  verbs:
  - update
- apiGroups:
  - hello.hello.io
  resources:
  - greeters/status
  verbs:
  - get
  - patch
  - update
