apiVersion: hello.hello.io/v1
kind: Greeter
metadata:
  labels:
    app.kubernetes.io/name: greeter-operator
    app.kubernetes.io/managed-by: kustomize
  name: greeter-sample
spec:
  # TODO(user): Add fields here
